add-jparepository-liquibase-ddlvalidate-softdelete-endpoints
andrey-kiyas/OnlineBookStore pull request #3
Opened 2023-08-13 01:16 UTC by andrey-kiyas

Added:
- JpaRepository
- Liquibase
- DDLvalidate
- Softdelete
- Endpoints

2023-08-14 10:16 UTC, Rommelua requested changes

2023-08-14 10:16 UTC, Rommelua commented on src/main/java/com/onlinebookstore/exception/DataProcessingException.java
> +public class DataProcessingException extends RuntimeException {
what is it for? I do not see usage.

2023-08-14 10:16 UTC, Rommelua commented on src/main/java/com/onlinebookstore/mapper/BookMapper.java
> +    })
```suggestion
```

2023-08-14 10:16 UTC, Rommelua commented on src/main/java/com/onlinebookstore/repository/book/BookSpecificationBuilder.java
> +
empty lines

2023-08-14 10:26 UTC, andrey-kiyas commented on src/main/java/com/onlinebookstore/mapper/BookMapper.java
> +    })
Without this part I get a checkstyle error: "BookMapper.java:[17,10] Unmapped target properties: "id, deleted""

2023-08-14 10:27 UTC, andrey-kiyas commented on src/main/java/com/onlinebookstore/repository/book/BookSpecificationBuilder.java
> +
Yes, sorry, corrected

2023-08-14 10:32 UTC, andrey-kiyas commented on src/main/java/com/onlinebookstore/mapper/BookMapper.java
> +    })
...but checkstyle plagin 3.1.2 solved this problem. Corrected.

2023-08-14 10:32 UTC, andrey-kiyas commented on src/main/java/com/onlinebookstore/exception/DataProcessingException.java
> +public class DataProcessingException extends RuntimeException {
Corrected, thanks!

2023-08-14 11:11 UTC, Rommelua requested changes

2023-08-14 11:11 UTC, Rommelua commented on src/main/java/com/onlinebookstore/repository/book/spec/DescriptionSpecificationProvider.java
> +public class DescriptionSpecificationProvider implements SpecificationProvider<Book> {
how it works? search by full Description?

2023-08-14 11:11 UTC, Rommelua commented on src/main/java/com/onlinebookstore/repository/book/spec/PriceSpecificationProvider.java
> +public class PriceSpecificationProvider implements SpecificationProvider<Book> {
Same. We need price bounds for searchI think (min/max)

2023-08-14 11:11 UTC, Rommelua commented on src/main/java/com/onlinebookstore/repository/book/spec/TitleSpecificationProvider.java
> +                .in(Arrays.stream(params).toArray());
let's use "like" logic for Title
for example when we have "master" in parameter we would like to see both
Master and Margarita and Master Your Emotions in the results

2023-08-14 15:34 UTC, andrey-kiyas commented on src/main/java/com/onlinebookstore/repository/book/spec/PriceSpecificationProvider.java
> +public class PriceSpecificationProvider implements SpecificationProvider<Book> {
Ok, added

2023-08-14 15:34 UTC, andrey-kiyas commented on src/main/java/com/onlinebookstore/repository/book/spec/TitleSpecificationProvider.java
> +                .in(Arrays.stream(params).toArray());
Done

2023-08-14 15:34 UTC, andrey-kiyas commented on src/main/java/com/onlinebookstore/repository/book/spec/DescriptionSpecificationProvider.java
> +public class DescriptionSpecificationProvider implements SpecificationProvider<Book> {
Yes, after last correction

2023-08-15 09:26 UTC, Rommelua approved these changes

2023-08-15 09:26 UTC, Rommelua commented on src/main/java/com/onlinebookstore/repository/book/spec/DescriptionSpecificationProvider.java
> +public class DescriptionSpecificationProvider implements SpecificationProvider<Book> {
I think this class can be deleted at all. I've never seen a search by Description. But as you wish

2023-08-15 10:44 UTC, merged